{
  lib,
  config,
  pkgs,
  isWork ? false,
  ...
}:

{
  options.registry.debian.packages =
    with lib;
    mkOption {
      type = types.listOf types.str;
      default = [ ];
      description = "A registry of packages to be installed natively on Debian systems.";
    };

  config = lib.mkIf (config.registry.debian.packages != [ ]) (
    let
      debianPackagesFile = pkgs.writeText "debian_packages.pp" ''
        # DO NOT EDIT. This file is generated by Home Manager.
        class debian_packages {
          package { [${
            lib.strings.concatStringsSep ", " (map (p: "'${p}'") config.registry.debian.packages)
          }]:
            ensure => installed,
          }
        }
        include debian_packages
      '';
    in
    {
      home.activation.copyDebianPackagesFile = lib.hm.dag.entryAfter ["writeBoundary"] ''
        $DRY_RUN_CMD mkdir -p "$HOME/.config/nix/scripts"
        $DRY_RUN_CMD cp -f "${debianPackagesFile}" "$HOME/.config/nix/scripts/debian_packages.pp"
      '';
    }
  );
}
