{
  lib,
  config,
  isWork ? false,
  ...
}:

{
  options.registry.debian.packages =
    with lib;
    mkOption {
      type = types.listOf types.str;
      default = [ ];
      description = "A registry of packages to be installed natively on Debian systems.";
    };

  config = lib.mkIf (config.registry.debian.packages != [ ]) {
    home.file.".config/nix/scripts/debian_packages.pp" = {
      text = ''
        # DO NOT EDIT. This file is generated by Home Manager.
        class debian_packages {
          package { [${
            lib.strings.concatStringsSep ", " (map (p: "'${p}'") config.registry.debian.packages)
          }]:
            ensure => installed,
          }
        }
        include debian_packages
      '';
    };
  };
}
