# DO NOT EDIT. This file is generated by Home Manager.
class debian_packages {
  package { ['ptyxis', 'google-chrome-stable', 'google-chrome-beta']:
    ensure => installed,
  }
}
include debian_packages
